.gitignore

add mockup folder to gitignore

add mockup folder to gitignore

---

css/offers.css
includes/marketAndOffers/offers.js
includes/marketAndOffers/offers.php
includes/marketAndOffers/offersProcess.php

1. Add crud operations:
- create
- read
- update
- delete
2. Add validations
3. Add basic style
***NOTES:***
> Hebrew comments refer to gaps that need to be filled after integrations.
> English comments refer to the code.

offers CRUD and basic FE

---

includes/general.js

Fix the parallax image bug in general.js

Fix the parallax image bug

---

includes/marketAndOffers/offers.js

- Check that price input is a positive number.
- Check that price input not contains punctuation. 
- Remove unnecessary validations.

Improving the input validations of 'price'

---

css/market.css
includes/marketAndOffers/market.php

- Ensure that relevant image of offer is exists
- Read relevant image and display it for each offer.
**NOTES:**
> Hebrew comments refer to gaps that need to be filled after integrations.
> English comments refer to the code.

Display offers image in market page

---

conection/Vendor.php
conection/config.php
conection/database.php
conection/init.php
conection/offer.php
conection/session.php
conection/users.php
conection/wishlist.php
css/HeadFoot.css
css/StoreStyle.css
css/register.css
css/style.css
includes/usersManagment/LogOut.php
includes/usersManagment/Login.php
includes/usersManagment/My_Account.php
includes/usersManagment/SignUp.php
includes/usersManagment/SignUp_User.php
includes/usersManagment/SignUp_Vendor.php
includes/usersManagment/Update_User.php
includes/usersManagment/Update_Vendor.php
index.php

updates files for all of the users management process, including connection document

[feat-9] users managment updates

---

includes/usersManagment/Login.php

[feat 10] update login page

---

css/Login.css

[feat 10] update register

---

includes/marketAndOffers/offersProcess.php

offersProcess page after integration with all the parts of the project

offersProcess page after integration

---

includes/marketAndOffers/market.php

market page after integration with all the parts of the project

market page after integration

---

includes/marketAndOffers/vendorDetails.php

vendorDetails page after integration with all the parts of the project

vendorDetails page after integration

---

css/signup.css
includes/usersManagment/SignUp.php
includes/usersManagment/SignUp_User.php
includes/usersManagment/SignUp_Vendor.php
includes/usersManagment/Update_User.php
includes/usersManagment/Update_Vendor.php

[feat 13] update signup css

---

css/hpStyle.css
css/signup.css
includes/usersManagment/SignUp_User.php
includes/usersManagment/SignUp_Vendor.php
includes/usersManagment/Update_User.php
includes/usersManagment/Update_Vendor.php
index.php

Updated css:
1. Responsive index
2. final css for signup user, signup vendor, update user, update vendor
3. updated css file for home page main index
4. updated signup css file

[fear 14] updated css

---

includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php
includes/marketAndOffers/vendorDetails.php
includes/marketAndOffers/vendorHomepage.php
includes/usersManagment/My_Account.php
index.php

Change the position of the navbar (fixed-->sticky) and adjust to the content of the page.
This change was not performed in the following directories: 
- regularUserHomepage
- tasksProcess

Change tha navbar position

---

conection/offer.php
css/offers.css
includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php
includes/marketAndOffers/offersProcess.php
includes/marketAndOffers/vendorDetails.php

- Market: Display only valid suggestions
- Offers: fix bugs after integration

Make necessary corrections market and offers

---

css/vendorHomepage.css
includes/marketAndOffers/vendorHomepage.php

Adding the folowing charts:
- pie chart- all offers by valid and not valid
- bar chart- wishlist that request for contact and only saved offers
- line chart- last 30 days offers by date
-  horizontal bar chart- wishlist per offer

Add dashboard to vendorHomepage

---

includes/usersManagment/SignUp.php

update slides position in SINGUP page

[feat 16] update signup page

---

includes/usersManagment/My_Account.php

[feat 17] update myaccount

---

includes/usersManagment/My_Account.php

updated see my account page including photos

[feat 18] updated seeMyAccount

---

css/market.css
includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php

Adding search bar to market.php
*The search is by offer name*

Add search bar to market page

---

includes/regularUserHomepage/regularUserHP.php
includes/tasksProcess/insertAndDelete.php
includes/tasksProcess/tasks.php

refactor navbar and directories

[feat-14] refactor navbar and directories

---

css/offers.css
includes/marketAndOffers/offers.php

Offers page:
- Add search bar by offer name
- Change cards design

Add search bar and change design

---

css/market.css
css/offers.css
includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php

- Add a message when no relevant offers are found (offers and market pages)
- Change location of message of delete,upadate and add record

Add message of no offers

---

includes/usersManagment/myAccount.php

updated css for  "See My Account" page

[feat 22] updated css myaccount

---

css/vendorDetails.css
includes/marketAndOffers/vendorDetails.php

- Fix navbar
- Add "go to market" button
- Add icons to vendor details
- Add swiper that display the offers of the vendor

Make design changes in vendorDetails page

---

index.php

[feat-24] index update

---

css/taskStyle.css

Feat 16 update task process responsive

---

includes/regularUserHomepage/regularUserHP.php
includes/tasksProcess/insertAndDelete.php
includes/tasksProcess/tasks.php
quickstart.php

set timezone to Asia/Jerusalem in tasks process and regular user homepage

[feat-17] set timezone to Asia/Jerusalem

---

css/market.css
includes/marketAndOffers/market.php
includes/marketAndOffers/wishlist.inc.php

alert when added offer to wishlist
alert when the offer already exists on the wishlist

[feat-18] added wishlist alerts

---

conection/Vendor.php
conection/users.php
css/Login.css
includes/usersManagment/Login.php

added CSS to alerts and changed the position of the alert

[feat-19] login alerts

---

css/wishList.css
includes/wishList/wishList.php

[feat 23] updated wihlist css

---

css/vendorHomepage.css
includes/marketAndOffers/vendorHomepage.php

- Add element to dashboard that shows the offers that about to expire in a week.
- Fix bugs of Division by zero

Add element and fix bugs

---

css/signup.css
includes/usersManagment/signUpUser.php
includes/usersManagment/signUpVendor.php
includes/usersManagment/updateUser.php
includes/usersManagment/updateVendor.php

updates css for signup + update css

[feat 25] update sign up css

---

includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php
includes/marketAndOffers/vendorDetails.php
includes/marketAndOffers/vendorHomepage.php
includes/navbarTemplate.php
includes/regularUserHomepage/regularUserHP.php
includes/tasksProcess/tasks.php
includes/wishList/wishList.php
index.php

add navbar template to:
1) vendor HP
2) couple hp
3) offers
4) wishlist
5) tasks

[feat-22] add navbar template

---

css/market.css
css/offers.css
css/vendorDetails.css
css/vendorHomepage.css
includes/marketAndOffers/market.php
includes/marketAndOffers/offers.php
includes/marketAndOffers/vendorDetails.php
includes/marketAndOffers/vendorHomepage.php
includes/navbarTemplate.php

**convert the following pages into fully responsive webpages:**
- market.php
- offers.php
- vendorDetails.php
- vendorHomepage.php

convert pages into fully responsive webpages

---

includes/wishList/update_wishList.php
includes/wishList/wishList.php

remove unnecessary func & comments

[feat-27] remove unnecessary func & comments
